name: Update Web UI
on:
  push:
    tags:
      - v*

jobs:
  update_web_ui:
    name: Update Web UI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: Create variables
        run: |
          echo "GEL_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout Web UI
        uses: actions/checkout@v2
        with:
          repository: 'aesop/aesop-web-ui'
          fetch-depth: 1
          ref: 'develop'
          token: ${{ secrets.X_GITHUB_TOKEN }}

      - name: Checkout private tools
        uses: actions/checkout@v2
        with:
          repository: aesop/aesop-github-action
          token: ${{ secrets.X_GITHUB_TOKEN }}
          path: actions

      - name: Update Gel
        uses: ./actions/create-pr
        with:
          TOKEN: ${{ secrets.X_GITHUB_TOKEN }}
          VERSION: ${{ env.GEL_VERSION }}
          CREATE_IN: 'aesop-web-ui'
          BASE_BRANCH: 'develop'
